function translateEnglish() {
    document.getElementById('menuAustralia').innerHTML = `Australia`
    document.getElementById('menuNewZealand').innerHTML = `New Zealand`
    document.getElementById('menuSouthAfrica').innerHTML = `South Africa`
    document.getElementById('menuNamibia').innerHTML = `Namibia`
    document.getElementById('menuDubai').innerHTML = `Cruise Dubai`
    document.getElementById('mainTitle').innerHTML = `Welcome to Simon's World Tour`
    document.getElementById('australiaTitle').innerHTML = `Australia:`
    document.getElementById('australiaText').innerHTML = `My dreamlike world trip began in Perth, Western Australia. From there, we traveled north to the Pink Lake in Port Gregory, Shell Beach in Albany, and many other attractions. We also explored the southern part of Western Australia. We visited the beautiful wine region of Margaret River and the stunning beaches in Esperance. Afterward, we flew to Cairns and started the second leg of our Australia trip from there. Over the course of 4 weeks, we traveled from Cairns to Sydney. The highlights of this leg include Fraser Island and the beautiful hiking areas and national parks. Here is a glimpse of my dreamlike trip to Australia, an unforgettable time!`
    document.getElementById('newzealandTitle').innerHTML = `New Zealand:`
    document.getElementById('newzealandText').innerHTML = `Our journey through New Zealand began in the capital city of Auckland. We explored both the North Island and the South Island. The breathtaking hikes, the diverse landscapes, and the different types of vegetation we encountered in New Zealand were particularly impressive. Another highlight was our visit to the Weta Workshop, a New Zealand-based special effects company located in Wellington. They offer services for film projects such as design concepts, make-up effects, props, creatures, puppets, miniatures, models, and large sculptures. They are known for films like King Kong and the Lord of the Rings and Hobbit series. Additionally, Weta Workshop also produces merchandise. The highlight of our trip was a day excursion to the fjords of New Zealand, specifically to Milford Sound. It was an unforgettable day on the boat, which left us deeply impressed by its beauty and uniqueness.`
    document.getElementById('southafricaTitle').innerHTML = `South Africa:`
    document.getElementById('southafricaText').innerHTML = `We started the New Year 2024 in South Africa's capital, Cape Town. From there, we explored the famous Garden Route, which delighted us with its picturesque landscapes and various wineries. A particularly memorable experience was our stay at a small lodge, where we had the unique opportunity to go for a walk with a majestic elephant. It was an unforgettable experience and one of the highlights of my world tour! South Africa is renowned not only for its wine and culinary culture but also for its impressive wildlife, a fact I can confirm after my trip.`
    document.getElementById('namibiaTitle').innerHTML = `Namibia:`
    document.getElementById('namibiaText').innerHTML = `The journey through Namibia was one of the most impressive travel experiences I have ever had. Highlights included the vast expanses of sand, the stunning landscapes, the Fish River Canyon in the south, and the Etosha National Park with its diverse wildlife. It was extremely impressive how the landscapes could change throughout the country and how friendly the people were to us. Namibia is definitely in the top 3 countries I have ever visited. It certainly won't be my last time there.`
    document.getElementById('dubaiTitle').innerHTML = `Cruise Dubai / Abu Dhabi / Oman`
    document.getElementById('dubaiText').innerHTML = `As the final leg of my world tour, I booked an MSC cruise from Abu Dhabi to Dubai and Oman. The cruise lasted 8 days and it was impressive to see all that had been built in the cities. Particularly impressive were the world's tallest building, the Burj Khalifa, and the huge shopping mall in Dubai. Everything in the cities was extremely well-maintained and clean. Unfortunately, the prices were extremely high, and the countries did not quite match my taste, which is why I would only recommend them to a limited extent.`
}

function translateGerman() {
    window.location.reload();
}

function translateDataProtectionEnglish() {
    document.getElementById('translateDataProtection1').innerHTML = `We place great importance on ensuring that the handling of personal data is transparent. This Privacy Policy provides information on which personal data we collect, for what purpose, and to whom we disclose it. To ensure a high level of transparency, this Privacy Policy is regularly reviewed and updated.`
    document.getElementById('translateDataProtection2').innerHTML = `1. The services we use` 
    document.getElementById('translateDataProtection3').innerHTML = `External services are not used on this website.`
    document.getElementById('translateDataProtection4').innerHTML = `2. Contact information`
    document.getElementById('translateDataProtection5').innerHTML = `If you have any questions or concerns regarding the protection of your data by us, you can reach us at any time via email at <a href="mailto:simi.matter@gmail.com">simi.matter@gmail.com</a>. The person responsible for data processing carried out through this website is:`
    document.getElementById('translateDataProtection6').innerHTML = `S. Matter<br />5436 Würenlos<br />Schweiz<br /><br /><strong>Data Protection Officer:</strong><br />S. Matter<br /><a href="mailto:simi.matter@gmail.com">simi.matter@gmail.com</a>`
    document.getElementById('translateDataProtection7').innerHTML = `3. General Principles`
    document.getElementById('translateDataProtection8').innerHTML = `Which data do we collect from you and from whom do we receive this data`
    document.getElementById('translateDataProtection9').innerHTML = `Primarily, we process personal data that you provide to us or that we collect during the operation of our website. In some cases, we also receive personal data about you from third parties. These may include the following categories:`
    document.getElementById('translateDataProtection10').innerHTML = `<li>Personal data (name, address, date of birth, etc.);</li><li>Contact details (mobile number, email address, etc.);</li><li>Financial data (e.g., account information);</li><li>Online identifiers (e.g., cookie ID, IP addresses);</li><li>Location and traffic data;</li><li>Audio and video recordings;</li>`
    document.getElementById('translateDataProtection11').innerHTML = `3.2 Under what conditions do we process your data?`
    document.getElementById('translateDataProtection12').innerHTML = `We handle your data confidentially and in accordance with the purposes specified in this Privacy Policy. We ensure a transparent and proportionate processing of data. If, exceptionally, we are unable to adhere to these principles, data processing may still be lawful if there is a justification for it. The following justifications may apply:`
    document.getElementById('translateDataProtection13').innerHTML = `<li>Your consent;</li><li>The performance of a contract or pre-contractual measures;</li><li>Our legitimate interests, provided that your interests do not outweigh them.</li></ul>`
    document.getElementById('translateDataProtection14').innerHTML = `3.3 How can you withdraw your consent?`
    document.getElementById('translateDataProtection15').innerHTML = `If you have given us consent to process your personal data for specific purposes, we will process your data within the scope of that consent, provided we do not have another justification. You can withdraw your consent at any time by sending an email to the address listed in the imprint. Data processing that has already occurred is not affected.`
    document.getElementById('translateDataProtection16').innerHTML = `3.4 In what cases can we share your data with third parties?`
    document.getElementById('translateDataProtection17').innerHTML = `a. Principle`
    document.getElementById('translateDataProtection18').innerHTML = `We may be dependent on using the services of third parties or affiliated companies and may commission them with processing your data (so-called processors). Categories of recipients include:`
    document.getElementById('translateDataProtection19').innerHTML = `<li>Accounting, fiduciary, and auditing companies;</li><li>Consulting companies (legal advice, taxes, etc.);</li><li>IT service providers (web hosting, support, cloud services, website design, etc.);</li><li>Payment service providers;</li><li>Providers of tracking, conversion, and advertising services.</li>`
    document.getElementById('translateDataProtection20').innerHTML = `We ensure that these third parties and our affiliated companies comply with data protection requirements and treat your personal data confidentially.<br /><br />In some cases, we are also obliged to disclose your personal data to authorities.`
    document.getElementById('translateDataProtection21').innerHTML = `b. Visiting our social media channels`
    document.getElementById('translateDataProtection22').innerHTML = `We may have embedded links to our social media channels on our website. This is usually evident (typically through corresponding icons). If you click on the icons, you will be redirected to our social media channels.<br /><br />In this case, the social media providers will know that you are accessing their platform from our website. The social media providers can use the data collected for their own purposes. We point out that we have no knowledge of the content of the transmitted data or its use by the operators.`
    document.getElementById('translateDataProtection23').innerHTML = `c. Transfer Abroad`
    document.getElementById('translateDataProtection24').innerHTML = `In the course of processing orders, it may be necessary to transfer your personal data to companies abroad. These companies are obliged to protect data to the same extent as we are. The transfer can take place worldwide.<br /><br />If the level of data protection does not correspond to that of Switzerland, we will conduct a prior risk assessment and contractually ensure that the same protection as in Switzerland is guaranteed (e.g., through the new standard contractual clauses of the EU Commission or other legally prescribed measures). If our risk assessment is negative, we will take additional technical measures to protect your data. You can access the EU Commission's standard contractual clauses via the following link:https://commission.europa.eu/publications/standard-contractual-clauses-controllers-and-processors-eueea_de`
    document.getElementById('translateDataProtection25').innerHTML = `3.5 How long do we retain your data?`
    document.getElementById('translateDataProtection26').innerHTML = `We store personal data only as long as it is necessary to fulfill the specific purposes for which the data was collected.<br /><br />Data that we store during your visit to our website is retained for twelve months. An exception applies to analysis and tracking data, which may be retained for a longer period.<br /><br />We store contract data for a longer period, as we are legally required to do so. In particular, we must retain business communications, concluded contracts, and accounting records for up to 10 years. If we no longer need such data from you for the provision of services, the data will be blocked and we will only use it for accounting and tax purposes.`
    document.getElementById('translateDataProtection27').innerHTML = `3.6 How do we protect your data?`
    document.getElementById('translateDataProtection28').innerHTML = `We will securely store your data and take all appropriate measures to protect it from loss, access, misuse, or alteration.<br /><br />Our partners and employees who have access to your data are obligated to comply with data protection regulations. In some cases, it will be necessary for us to forward your requests to affiliated companies. Even in these cases, your data will be treated confidentially.<br /><br />On our website, we use the SSL (Secure Socket Layer) protocol in conjunction with the highest encryption level supported by your browser.`
    document.getElementById('translateDataProtection29').innerHTML = `3.7 What rights do you have?`
    document.getElementById('translateDataProtection30').innerHTML = `a. Right to Access`
    document.getElementById('translateDataProtection31').innerHTML = `You can request information about the data we hold about you at any time. We ask that you send your request for information along with proof of identity to simi.matter@gmail.com.<br><br/>You also have the right to receive your data in a commonly used format if we process your data automatically, and if:`
    document.getElementById('translateDataProtection32').innerHTML = `<li>You have given your consent for the processing of this data; or/li>li> You have provided data in connection with the conclusion or execution of a contract./li>`
    document.getElementById('translateDataProtection33').innerHTML = `We may restrict or deny the disclosure of information or data if it conflicts with our legal obligations, legitimate own or public interests, or the interests of a third party.<br /><br />The processing of your request is subject to the statutory processing period of 30 days. However, we may extend this period due to high request volumes, legal or technical reasons, or if we require additional information from you. You will be informed in a timely manner, at least in text form, about any extension of the deadline.`
    document.getElementById('translateDataProtection34').innerHTML = `b. Deletion and Correction`
    document.getElementById('translateDataProtection35').innerHTML = `You have the right to request the deletion or correction of your data at any time. We may refuse the request if legal regulations require us to retain the data for a longer period or if a legal basis contradicts your request.<br /><br />Please note that exercising your rights may, in some cases, conflict with contractual agreements and could have implications for the execution of the contract (e.g., premature termination of the contract or cost consequences).`
    document.getElementById('translateDataProtection36').innerHTML = `c. Legal Recourse`
    document.getElementById('translateDataProtection37').innerHTML = `If you are affected by the processing of personal data, you have the right to enforce your rights through legal action or to file a complaint with the competent supervisory authority. The competent supervisory authority in Switzerland is the Federal Data Protection and Information Commissioner: https://www.edoeb.admin.ch`
    document.getElementById('translateDataProtection38').innerHTML = `3.8 Changes to the Privacy Policy`
    document.getElementById('translateDataProtection39').innerHTML = `We may change this privacy policy at any time. The changes will be published, and you will not be notified separately.`
    document.getElementById('translateDataProtection40').innerHTML = `4. Specific Data Processing Activities`
    document.getElementById('translateDataProtection41').innerHTML = `4.1 Providing the Website and Creating Log Files`
    document.getElementById('translateDataProtection42').innerHTML = `What information do we collect and how do we use it?`
    document.getElementById('translateDataProtection43').innerHTML = `When you visit, certain data is automatically stored on our servers or on the servers of services and products that we use and/or have installed, for purposes of system administration, statistical or backup purposes, or for tracking purposes. This includes:`
    document.getElementById('translateDataProtection44').innerHTML = `<li>the name of your internet service provider;</li><li>your IP address (if applicable);</li><li>the version of your browser software;</li><li>the operating system of the computer used to access the URL;</li><li>the date and time of access;</li><li>the website from which you accessed the URL;</li><li>the search terms you used to find the URL.</li>`
    document.getElementById('translateDataProtection45').innerHTML = `Why are we allowed to process this data?`
    document.getElementById('translateDataProtection46').innerHTML = `This data cannot be attributed to any specific individual, and there is no merging of this data with other data sources. The storage of log files is carried out to ensure the functionality of the website and to ensure the security of our information technology systems. This constitutes our legitimate interest.`
    document.getElementById('translateDataProtection47').innerHTML = `How can you prevent data collection?`
    document.getElementById('translateDataProtection48').innerHTML = `The data is stored only as long as necessary to achieve the purpose of its collection. Accordingly, the data is deleted after each session ends. The storage of log files is essential for the operation of the website, and therefore, you do not have the option to object to this.`
}

function translateDataProtectionGerman() {
    window.location.reload();
}


function translateImprintEnglish() {
    document.getElementById('translateImprint1').innerHTML = `<b>Responsible Entity:</b><br>
S. Matter<br>5436 Würenlos<br>Switzerland<br><strong>Email:</strong> simi.matter@gmail.com<br><br><strong>Disclaimer</strong><br>
The author assumes no responsibility for the accuracy, correctness, timeliness, reliability, or completeness of the information. Liability claims against the author for material or immaterial damages resulting from access to or use or non-use of the published information, through misuse of the connection, or through technical disturbances are excluded.<br><br>All offers are non-binding. The author expressly reserves the right to change, supplement, delete, or temporarily or permanently discontinue the publication of parts of the pages or the entire offer without prior notice.<br><br><strong>Disclaimer for Content and Links</strong><br>
References and links to third-party websites are outside our area of responsibility. Any responsibility for such websites is disclaimed. Access to and use of such websites is at the user's own risk.<br><br><strong>Copyright Notice</strong><br>
The copyrights and all other rights to content, images, photos, or other files on this website belong exclusively to Simon Matter or the specifically mentioned rights holders. Reproduction of any elements requires prior written consent from the copyright holder.` 
}

function translateImprintGerman() {
    window.location.reload();
}